version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3001
      - HOST=0.0.0.0
    networks:
      - app
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    env_file:
      - .env
    environment:
      - PORT=3000
      - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
      - INTERNAL_BACKEND_URL=http://api:3001
    depends_on:
      - api
    networks:
      - app
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - api
    networks:
      - app
    restart: unless-stopped

networks:
  app:
    driver: bridge


