name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || 22 }}
          script: |
            echo "🚀 Starting deployment..."
            
            # Navigate to project directory
            cd ${{ secrets.PROJECT_PATH || '~/yellow-book' }}
            
            # Pull latest changes
            echo "📦 Pulling latest changes from main..."
            git pull origin main
            
            # Stop and remove containers
            echo "🛑 Stopping containers..."
            docker compose down
            
            # Rebuild and start containers
            echo "🔨 Building and starting containers..."
            docker compose up --build -d
            
            # Show running containers
            echo "✅ Deployment complete! Running containers:"
            docker compose ps
            
            # Optional: Clean up old images to save space
            echo "🧹 Cleaning up old Docker images..."
            docker image prune -f

